### ISSUE TITLE
Overall: Header seems to jump

### ISSUE THREAD

**Issue by derhackler** [derhackler/nikolauseckhard#3]
The header seems to jump by a few pixes when you navigate from the homepage to a project page. Does not seem to happen on small screens though.

**Comment by kallaballa** [comment]
The nav header was jumping because the page-width changed with the appearance of a vertical scrollbar. I fixed it by calculating the width of the scrollbar and left-padding the page by that amount.

e12f680332a286e34a52448b2928ae22752cdf26
